layout_spectrum: 1
typography_spectrum: 0.08297873
color:
  lightness: 0.6829787
  brandStrength: 0.09704856
  saturation: 0.6680851
  rhythmicContrast: 0.8255319
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: 'Anna Wikman  Fotografi  '
