layout_spectrum: 1
typography_spectrum: 0.08297873
color:
  lightness: 0.6829787
  brandStrength: 1
  saturation: 0.6680851
  rhythmicContrast: 0.8255319
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
name: 'Anna Wikman  Fotografi  '
